[project]
name = "mcp-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp-use>=1.4.0",
    "mcp[cli]>=1.20.0",
]
